/** ClickHouse built-in functions for autocomplete. */

import type { CatalogFunction } from "../types";

export const CH_FUNCTIONS: CatalogFunction[] = [
    // Aggregate functions
    { name: "count", signature: "count(expression)", description: "Number of rows", category: "aggregate" },
    { name: "sum", signature: "sum(expression)", description: "Sum of values", category: "aggregate" },
    { name: "avg", signature: "avg(expression)", description: "Average of values", category: "aggregate" },
    { name: "min", signature: "min(expression)", description: "Minimum value", category: "aggregate" },
    { name: "max", signature: "max(expression)", description: "Maximum value", category: "aggregate" },
    { name: "any", signature: "any(expression)", description: "First encountered value", category: "aggregate" },
    { name: "anyLast", signature: "anyLast(expression)", description: "Last encountered value", category: "aggregate" },
    { name: "groupArray", signature: "groupArray(expression)", description: "Collect values into array", category: "aggregate" },
    { name: "groupUniqArray", signature: "groupUniqArray(expression)", description: "Collect unique values into array", category: "aggregate" },
    { name: "uniq", signature: "uniq(expression)", description: "Approximate unique count", category: "aggregate" },
    { name: "uniqExact", signature: "uniqExact(expression)", description: "Exact unique count", category: "aggregate" },
    { name: "uniqHLL12", signature: "uniqHLL12(expression)", description: "HyperLogLog unique count", category: "aggregate" },
    { name: "uniqCombined", signature: "uniqCombined(expression)", description: "Combined unique count", category: "aggregate" },
    { name: "argMin", signature: "argMin(arg, val)", description: "arg value at minimum val", category: "aggregate" },
    { name: "argMax", signature: "argMax(arg, val)", description: "arg value at maximum val", category: "aggregate" },
    { name: "sumMap", signature: "sumMap(keys, values)", description: "Sum values grouped by keys", category: "aggregate" },
    { name: "quantile", signature: "quantile(level)(expression)", description: "Quantile at level", category: "aggregate" },
    { name: "quantiles", signature: "quantiles(levels...)(expression)", description: "Multiple quantiles", category: "aggregate" },
    { name: "median", signature: "median(expression)", description: "Median value", category: "aggregate" },
    { name: "topK", signature: "topK(N)(expression)", description: "Top N frequent values", category: "aggregate" },
    { name: "groupBitAnd", signature: "groupBitAnd(expression)", description: "Bitwise AND across group", category: "aggregate" },
    { name: "groupBitOr", signature: "groupBitOr(expression)", description: "Bitwise OR across group", category: "aggregate" },
    { name: "groupBitXor", signature: "groupBitXor(expression)", description: "Bitwise XOR across group", category: "aggregate" },

    // Window functions
    { name: "row_number", signature: "row_number()", description: "Row number within partition", category: "window" },
    { name: "rank", signature: "rank()", description: "Rank with gaps", category: "window" },
    { name: "dense_rank", signature: "dense_rank()", description: "Rank without gaps", category: "window" },
    { name: "ntile", signature: "ntile(n)", description: "Divide rows into n buckets", category: "window" },
    { name: "lag", signature: "lag(value, offset, default)", description: "Access preceding row", category: "window" },
    { name: "lead", signature: "lead(value, offset, default)", description: "Access following row", category: "window" },
    { name: "first_value", signature: "first_value(expression)", description: "First value in window frame", category: "window" },
    { name: "last_value", signature: "last_value(expression)", description: "Last value in window frame", category: "window" },

    // String functions
    { name: "length", signature: "length(string)", description: "String length in bytes", category: "string" },
    { name: "lengthUTF8", signature: "lengthUTF8(string)", description: "String length in UTF-8 characters", category: "string" },
    { name: "lower", signature: "lower(string)", description: "Lowercase", category: "string" },
    { name: "upper", signature: "upper(string)", description: "Uppercase", category: "string" },
    { name: "concat", signature: "concat(s1, s2, ...)", description: "Concatenate strings", category: "string" },
    { name: "substring", signature: "substring(s, offset, length)", description: "Extract substring", category: "string" },
    { name: "trim", signature: "trim(string)", description: "Remove whitespace", category: "string" },
    { name: "splitByChar", signature: "splitByChar(separator, s)", description: "Split string by character", category: "string" },
    { name: "splitByString", signature: "splitByString(separator, s)", description: "Split string by string", category: "string" },
    { name: "replaceAll", signature: "replaceAll(haystack, pattern, replacement)", description: "Replace all occurrences", category: "string" },
    { name: "replaceOne", signature: "replaceOne(haystack, pattern, replacement)", description: "Replace first occurrence", category: "string" },
    { name: "replaceRegexpAll", signature: "replaceRegexpAll(haystack, pattern, replacement)", description: "Regex replace all", category: "string" },
    { name: "match", signature: "match(haystack, pattern)", description: "Regex match (returns 0/1)", category: "string" },
    { name: "extract", signature: "extract(haystack, pattern)", description: "Extract regex match", category: "string" },
    { name: "like", signature: "like(haystack, pattern)", description: "LIKE pattern match", category: "string" },
    { name: "notLike", signature: "notLike(haystack, pattern)", description: "NOT LIKE pattern match", category: "string" },
    { name: "position", signature: "position(haystack, needle)", description: "Position of substring", category: "string" },
    { name: "reverse", signature: "reverse(string)", description: "Reverse string", category: "string" },
    { name: "format", signature: "format(pattern, args...)", description: "Format string", category: "string" },
    { name: "base64Encode", signature: "base64Encode(string)", description: "Encode to base64", category: "string" },
    { name: "base64Decode", signature: "base64Decode(string)", description: "Decode from base64", category: "string" },

    // Date/time functions
    { name: "now", signature: "now()", description: "Current date and time", category: "datetime" },
    { name: "today", signature: "today()", description: "Current date", category: "datetime" },
    { name: "yesterday", signature: "yesterday()", description: "Yesterday's date", category: "datetime" },
    { name: "toDate", signature: "toDate(expression)", description: "Convert to Date", category: "datetime" },
    { name: "toDateTime", signature: "toDateTime(expression)", description: "Convert to DateTime", category: "datetime" },
    { name: "toDateTime64", signature: "toDateTime64(expression, precision)", description: "Convert to DateTime64", category: "datetime" },
    { name: "toYear", signature: "toYear(date)", description: "Extract year", category: "datetime" },
    { name: "toMonth", signature: "toMonth(date)", description: "Extract month", category: "datetime" },
    { name: "toDayOfMonth", signature: "toDayOfMonth(date)", description: "Extract day of month", category: "datetime" },
    { name: "toDayOfWeek", signature: "toDayOfWeek(date)", description: "Day of week (1=Monday)", category: "datetime" },
    { name: "toHour", signature: "toHour(datetime)", description: "Extract hour", category: "datetime" },
    { name: "toMinute", signature: "toMinute(datetime)", description: "Extract minute", category: "datetime" },
    { name: "toSecond", signature: "toSecond(datetime)", description: "Extract second", category: "datetime" },
    { name: "toStartOfDay", signature: "toStartOfDay(datetime)", description: "Truncate to start of day", category: "datetime" },
    { name: "toStartOfWeek", signature: "toStartOfWeek(date)", description: "Truncate to start of week", category: "datetime" },
    { name: "toStartOfMonth", signature: "toStartOfMonth(date)", description: "Truncate to start of month", category: "datetime" },
    { name: "toStartOfYear", signature: "toStartOfYear(date)", description: "Truncate to start of year", category: "datetime" },
    { name: "toStartOfHour", signature: "toStartOfHour(datetime)", description: "Truncate to start of hour", category: "datetime" },
    { name: "toStartOfMinute", signature: "toStartOfMinute(datetime)", description: "Truncate to start of minute", category: "datetime" },
    { name: "toStartOfInterval", signature: "toStartOfInterval(date, INTERVAL n unit)", description: "Truncate to interval", category: "datetime" },
    { name: "dateDiff", signature: "dateDiff(unit, start, end)", description: "Difference between dates", category: "datetime" },
    { name: "dateAdd", signature: "dateAdd(unit, amount, date)", description: "Add interval to date", category: "datetime" },
    { name: "dateSub", signature: "dateSub(unit, amount, date)", description: "Subtract interval from date", category: "datetime" },
    { name: "formatDateTime", signature: "formatDateTime(datetime, format)", description: "Format datetime as string", category: "datetime" },
    { name: "parseDateTimeBestEffort", signature: "parseDateTimeBestEffort(string)", description: "Parse datetime string", category: "datetime" },

    // Math functions
    { name: "abs", signature: "abs(x)", description: "Absolute value", category: "math" },
    { name: "ceil", signature: "ceil(x)", description: "Ceiling", category: "math" },
    { name: "floor", signature: "floor(x)", description: "Floor", category: "math" },
    { name: "round", signature: "round(x, n)", description: "Round to n decimals", category: "math" },
    { name: "sqrt", signature: "sqrt(x)", description: "Square root", category: "math" },
    { name: "pow", signature: "pow(x, y)", description: "Power", category: "math" },
    { name: "log", signature: "log(x)", description: "Natural logarithm", category: "math" },
    { name: "log2", signature: "log2(x)", description: "Log base 2", category: "math" },
    { name: "log10", signature: "log10(x)", description: "Log base 10", category: "math" },
    { name: "exp", signature: "exp(x)", description: "e^x", category: "math" },
    { name: "intDiv", signature: "intDiv(a, b)", description: "Integer division", category: "math" },
    { name: "intDivOrZero", signature: "intDivOrZero(a, b)", description: "Integer division (0 on divide-by-zero)", category: "math" },
    { name: "modulo", signature: "modulo(a, b)", description: "Modulo", category: "math" },

    // Type conversion
    { name: "toUInt8", signature: "toUInt8(expression)", description: "Convert to UInt8", category: "conversion" },
    { name: "toUInt16", signature: "toUInt16(expression)", description: "Convert to UInt16", category: "conversion" },
    { name: "toUInt32", signature: "toUInt32(expression)", description: "Convert to UInt32", category: "conversion" },
    { name: "toUInt64", signature: "toUInt64(expression)", description: "Convert to UInt64", category: "conversion" },
    { name: "toInt8", signature: "toInt8(expression)", description: "Convert to Int8", category: "conversion" },
    { name: "toInt16", signature: "toInt16(expression)", description: "Convert to Int16", category: "conversion" },
    { name: "toInt32", signature: "toInt32(expression)", description: "Convert to Int32", category: "conversion" },
    { name: "toInt64", signature: "toInt64(expression)", description: "Convert to Int64", category: "conversion" },
    { name: "toFloat32", signature: "toFloat32(expression)", description: "Convert to Float32", category: "conversion" },
    { name: "toFloat64", signature: "toFloat64(expression)", description: "Convert to Float64", category: "conversion" },
    { name: "toString", signature: "toString(expression)", description: "Convert to String", category: "conversion" },
    { name: "toDecimal32", signature: "toDecimal32(expression, S)", description: "Convert to Decimal32", category: "conversion" },
    { name: "toDecimal64", signature: "toDecimal64(expression, S)", description: "Convert to Decimal64", category: "conversion" },
    { name: "toDecimal128", signature: "toDecimal128(expression, S)", description: "Convert to Decimal128", category: "conversion" },
    { name: "cast", signature: "cast(x, T)", description: "Convert type", category: "conversion" },
    { name: "toTypeName", signature: "toTypeName(expression)", description: "Get type name as string", category: "conversion" },

    // Array functions
    { name: "arrayJoin", signature: "arrayJoin(array)", description: "Unfold array into rows", category: "array" },
    { name: "array", signature: "array(x1, x2, ...)", description: "Create array", category: "array" },
    { name: "arrayElement", signature: "arrayElement(arr, n)", description: "Get element by index", category: "array" },
    { name: "has", signature: "has(arr, elem)", description: "Check if array has element", category: "array" },
    { name: "hasAll", signature: "hasAll(set, subset)", description: "Check if set contains all subset elements", category: "array" },
    { name: "hasAny", signature: "hasAny(arr1, arr2)", description: "Check if arrays share any element", category: "array" },
    { name: "indexOf", signature: "indexOf(arr, x)", description: "Index of element in array", category: "array" },
    { name: "arrayConcat", signature: "arrayConcat(arr1, arr2, ...)", description: "Concatenate arrays", category: "array" },
    { name: "arrayFilter", signature: "arrayFilter(func, arr)", description: "Filter array by predicate", category: "array" },
    { name: "arrayMap", signature: "arrayMap(func, arr)", description: "Map function over array", category: "array" },
    { name: "arraySort", signature: "arraySort(arr)", description: "Sort array", category: "array" },
    { name: "arrayReverse", signature: "arrayReverse(arr)", description: "Reverse array", category: "array" },
    { name: "arrayDistinct", signature: "arrayDistinct(arr)", description: "Remove duplicates", category: "array" },
    { name: "arrayFlatten", signature: "arrayFlatten(arr)", description: "Flatten nested arrays", category: "array" },
    { name: "arrayStringConcat", signature: "arrayStringConcat(arr, separator)", description: "Join array to string", category: "array" },
    { name: "length", signature: "length(arr)", description: "Array length", category: "array" },
    { name: "empty", signature: "empty(arr)", description: "Check if array is empty", category: "array" },
    { name: "notEmpty", signature: "notEmpty(arr)", description: "Check if array is not empty", category: "array" },

    // JSON functions
    { name: "JSONExtract", signature: "JSONExtract(json, type)", description: "Extract typed value from JSON", category: "json" },
    { name: "JSONExtractString", signature: "JSONExtractString(json, path...)", description: "Extract string from JSON", category: "json" },
    { name: "JSONExtractInt", signature: "JSONExtractInt(json, path...)", description: "Extract integer from JSON", category: "json" },
    { name: "JSONExtractFloat", signature: "JSONExtractFloat(json, path...)", description: "Extract float from JSON", category: "json" },
    { name: "JSONExtractBool", signature: "JSONExtractBool(json, path...)", description: "Extract boolean from JSON", category: "json" },
    { name: "JSONExtractRaw", signature: "JSONExtractRaw(json, path...)", description: "Extract raw JSON fragment", category: "json" },
    { name: "JSONExtractArrayRaw", signature: "JSONExtractArrayRaw(json, path...)", description: "Extract JSON array as strings", category: "json" },
    { name: "JSONHas", signature: "JSONHas(json, path...)", description: "Check if path exists in JSON", category: "json" },
    { name: "JSONLength", signature: "JSONLength(json, path...)", description: "Length of JSON array/object", category: "json" },
    { name: "JSONType", signature: "JSONType(json, path...)", description: "Type of JSON value", category: "json" },

    // Hash functions
    { name: "cityHash64", signature: "cityHash64(value...)", description: "CityHash64", category: "hash" },
    { name: "sipHash64", signature: "sipHash64(value...)", description: "SipHash64", category: "hash" },
    { name: "MD5", signature: "MD5(string)", description: "MD5 hash", category: "hash" },
    { name: "SHA256", signature: "SHA256(string)", description: "SHA-256 hash", category: "hash" },
    { name: "xxHash64", signature: "xxHash64(value...)", description: "xxHash64", category: "hash" },

    // URL functions
    { name: "domain", signature: "domain(url)", description: "Extract domain from URL", category: "url" },
    { name: "path", signature: "path(url)", description: "Extract path from URL", category: "url" },
    { name: "protocol", signature: "protocol(url)", description: "Extract protocol from URL", category: "url" },
    { name: "extractURLParameter", signature: "extractURLParameter(url, name)", description: "Extract URL parameter", category: "url" },

    // Conditional
    { name: "if", signature: "if(cond, then, else)", description: "Conditional expression", category: "conditional" },
    { name: "multiIf", signature: "multiIf(cond1, then1, cond2, then2, ..., else)", description: "Multiple conditions", category: "conditional" },
    { name: "coalesce", signature: "coalesce(x1, x2, ...)", description: "First non-null value", category: "conditional" },
    { name: "ifNull", signature: "ifNull(x, alt)", description: "Replace null", category: "conditional" },
    { name: "nullIf", signature: "nullIf(x, y)", description: "Return null if x equals y", category: "conditional" },
    { name: "assumeNotNull", signature: "assumeNotNull(x)", description: "Remove Nullable wrapper", category: "conditional" },
    { name: "toNullable", signature: "toNullable(x)", description: "Wrap in Nullable", category: "conditional" },

    // Table functions
    { name: "numbers", signature: "numbers(N)", description: "Generate sequence 0..N-1", category: "table" },
    { name: "zeros", signature: "zeros(N)", description: "Generate N rows of zeros", category: "table" },
    { name: "generateRandom", signature: "generateRandom(structure, limit)", description: "Generate random data", category: "table" },

    // Other
    { name: "tuple", signature: "tuple(x1, x2, ...)", description: "Create tuple", category: "other" },
    { name: "dictGet", signature: "dictGet(dict_name, attr, key)", description: "Get value from dictionary", category: "other" },
    { name: "dictHas", signature: "dictHas(dict_name, key)", description: "Check if key in dictionary", category: "other" },
    { name: "sleep", signature: "sleep(seconds)", description: "Sleep for N seconds", category: "other" },
    { name: "version", signature: "version()", description: "ClickHouse version", category: "other" },
    { name: "currentDatabase", signature: "currentDatabase()", description: "Current database name", category: "other" },
    { name: "hostName", signature: "hostName()", description: "Server hostname", category: "other" },
];
