/** Common PostgreSQL built-in functions with signatures for autocomplete. */

export interface PgFunction {
    name: string;
    signature: string;
    description: string;
    category: string;
}

export const PG_FUNCTIONS: PgFunction[] = [
    // Aggregate functions
    { name: "count", signature: "count(expression)", description: "Number of rows", category: "aggregate" },
    { name: "sum", signature: "sum(expression)", description: "Sum of values", category: "aggregate" },
    { name: "avg", signature: "avg(expression)", description: "Average of values", category: "aggregate" },
    { name: "min", signature: "min(expression)", description: "Minimum value", category: "aggregate" },
    { name: "max", signature: "max(expression)", description: "Maximum value", category: "aggregate" },
    { name: "array_agg", signature: "array_agg(expression)", description: "Collect values into array", category: "aggregate" },
    { name: "string_agg", signature: "string_agg(expression, delimiter)", description: "Concatenate with delimiter", category: "aggregate" },
    { name: "bool_and", signature: "bool_and(expression)", description: "True if all true", category: "aggregate" },
    { name: "bool_or", signature: "bool_or(expression)", description: "True if any true", category: "aggregate" },
    { name: "json_agg", signature: "json_agg(expression)", description: "Aggregate values as JSON array", category: "aggregate" },
    { name: "jsonb_agg", signature: "jsonb_agg(expression)", description: "Aggregate values as JSONB array", category: "aggregate" },
    { name: "json_object_agg", signature: "json_object_agg(key, value)", description: "Aggregate key/value as JSON object", category: "aggregate" },
    { name: "jsonb_object_agg", signature: "jsonb_object_agg(key, value)", description: "Aggregate key/value as JSONB object", category: "aggregate" },

    // Window functions
    { name: "row_number", signature: "row_number()", description: "Row number within partition", category: "window" },
    { name: "rank", signature: "rank()", description: "Rank with gaps", category: "window" },
    { name: "dense_rank", signature: "dense_rank()", description: "Rank without gaps", category: "window" },
    { name: "ntile", signature: "ntile(n)", description: "Divide rows into n buckets", category: "window" },
    { name: "lag", signature: "lag(value, offset, default)", description: "Access preceding row", category: "window" },
    { name: "lead", signature: "lead(value, offset, default)", description: "Access following row", category: "window" },
    { name: "first_value", signature: "first_value(expression)", description: "First value in window frame", category: "window" },
    { name: "last_value", signature: "last_value(expression)", description: "Last value in window frame", category: "window" },
    { name: "nth_value", signature: "nth_value(expression, n)", description: "Nth value in window frame", category: "window" },
    { name: "percent_rank", signature: "percent_rank()", description: "Relative rank (0-1)", category: "window" },
    { name: "cume_dist", signature: "cume_dist()", description: "Cumulative distribution", category: "window" },

    // String functions
    { name: "length", signature: "length(string)", description: "String length", category: "string" },
    { name: "lower", signature: "lower(string)", description: "Convert to lowercase", category: "string" },
    { name: "upper", signature: "upper(string)", description: "Convert to uppercase", category: "string" },
    { name: "trim", signature: "trim(string)", description: "Remove leading/trailing whitespace", category: "string" },
    { name: "ltrim", signature: "ltrim(string, characters)", description: "Remove leading characters", category: "string" },
    { name: "rtrim", signature: "rtrim(string, characters)", description: "Remove trailing characters", category: "string" },
    { name: "substring", signature: "substring(string, start, length)", description: "Extract substring", category: "string" },
    { name: "replace", signature: "replace(string, from, to)", description: "Replace occurrences", category: "string" },
    { name: "concat", signature: "concat(val1, val2, ...)", description: "Concatenate values", category: "string" },
    { name: "concat_ws", signature: "concat_ws(sep, val1, val2, ...)", description: "Concatenate with separator", category: "string" },
    { name: "left", signature: "left(string, n)", description: "First n characters", category: "string" },
    { name: "right", signature: "right(string, n)", description: "Last n characters", category: "string" },
    { name: "repeat", signature: "repeat(string, n)", description: "Repeat string n times", category: "string" },
    { name: "reverse", signature: "reverse(string)", description: "Reverse string", category: "string" },
    { name: "position", signature: "position(substring IN string)", description: "Location of substring", category: "string" },
    { name: "strpos", signature: "strpos(string, substring)", description: "Location of substring", category: "string" },
    { name: "split_part", signature: "split_part(string, delimiter, n)", description: "Split and return nth part", category: "string" },
    { name: "regexp_replace", signature: "regexp_replace(string, pattern, replacement)", description: "Regex replace", category: "string" },
    { name: "regexp_matches", signature: "regexp_matches(string, pattern)", description: "Regex matches", category: "string" },
    { name: "regexp_split_to_table", signature: "regexp_split_to_table(string, pattern)", description: "Split by regex into rows", category: "string" },
    { name: "regexp_split_to_array", signature: "regexp_split_to_array(string, pattern)", description: "Split by regex into array", category: "string" },
    { name: "initcap", signature: "initcap(string)", description: "Capitalize first letter of each word", category: "string" },
    { name: "lpad", signature: "lpad(string, length, fill)", description: "Left-pad to length", category: "string" },
    { name: "rpad", signature: "rpad(string, length, fill)", description: "Right-pad to length", category: "string" },
    { name: "encode", signature: "encode(data, format)", description: "Encode binary to text", category: "string" },
    { name: "decode", signature: "decode(string, format)", description: "Decode text to binary", category: "string" },
    { name: "md5", signature: "md5(string)", description: "MD5 hash", category: "string" },
    { name: "format", signature: "format(formatstr, ...)", description: "Format string (printf-style)", category: "string" },
    { name: "translate", signature: "translate(string, from, to)", description: "Character-by-character translation", category: "string" },

    // Numeric / math
    { name: "abs", signature: "abs(n)", description: "Absolute value", category: "math" },
    { name: "ceil", signature: "ceil(n)", description: "Round up to integer", category: "math" },
    { name: "ceiling", signature: "ceiling(n)", description: "Round up to integer", category: "math" },
    { name: "floor", signature: "floor(n)", description: "Round down to integer", category: "math" },
    { name: "round", signature: "round(n, decimals)", description: "Round to decimals", category: "math" },
    { name: "trunc", signature: "trunc(n, decimals)", description: "Truncate to decimals", category: "math" },
    { name: "mod", signature: "mod(a, b)", description: "Remainder", category: "math" },
    { name: "power", signature: "power(base, exp)", description: "Raise to power", category: "math" },
    { name: "sqrt", signature: "sqrt(n)", description: "Square root", category: "math" },
    { name: "log", signature: "log(base, n)", description: "Logarithm", category: "math" },
    { name: "ln", signature: "ln(n)", description: "Natural logarithm", category: "math" },
    { name: "random", signature: "random()", description: "Random value 0.0–1.0", category: "math" },
    { name: "sign", signature: "sign(n)", description: "Sign of number (-1, 0, 1)", category: "math" },
    { name: "greatest", signature: "greatest(val1, val2, ...)", description: "Largest value", category: "math" },
    { name: "least", signature: "least(val1, val2, ...)", description: "Smallest value", category: "math" },
    { name: "generate_series", signature: "generate_series(start, stop, step)", description: "Generate series of values", category: "math" },

    // Date/time functions
    { name: "now", signature: "now()", description: "Current timestamp", category: "datetime" },
    { name: "current_date", signature: "current_date", description: "Current date", category: "datetime" },
    { name: "current_time", signature: "current_time", description: "Current time", category: "datetime" },
    { name: "current_timestamp", signature: "current_timestamp", description: "Current timestamp", category: "datetime" },
    { name: "clock_timestamp", signature: "clock_timestamp()", description: "Current timestamp (changes during statement)", category: "datetime" },
    { name: "date_trunc", signature: "date_trunc(field, source)", description: "Truncate to precision", category: "datetime" },
    { name: "date_part", signature: "date_part(field, source)", description: "Extract field from timestamp", category: "datetime" },
    { name: "extract", signature: "extract(field FROM source)", description: "Extract field from timestamp", category: "datetime" },
    { name: "age", signature: "age(timestamp, timestamp)", description: "Interval between timestamps", category: "datetime" },
    { name: "to_char", signature: "to_char(value, format)", description: "Format value as text", category: "datetime" },
    { name: "to_date", signature: "to_date(text, format)", description: "Parse text to date", category: "datetime" },
    { name: "to_timestamp", signature: "to_timestamp(text, format)", description: "Parse text to timestamp", category: "datetime" },
    { name: "to_number", signature: "to_number(text, format)", description: "Parse text to number", category: "datetime" },
    { name: "make_date", signature: "make_date(year, month, day)", description: "Construct date", category: "datetime" },
    { name: "make_interval", signature: "make_interval(years, months, ...)", description: "Construct interval", category: "datetime" },
    { name: "make_timestamp", signature: "make_timestamp(year, month, day, hour, min, sec)", description: "Construct timestamp", category: "datetime" },
    { name: "timezone", signature: "timezone(zone, timestamp)", description: "Convert to timezone", category: "datetime" },

    // JSON functions
    { name: "json_build_object", signature: "json_build_object(key1, val1, ...)", description: "Build JSON object", category: "json" },
    { name: "jsonb_build_object", signature: "jsonb_build_object(key1, val1, ...)", description: "Build JSONB object", category: "json" },
    { name: "json_build_array", signature: "json_build_array(val1, ...)", description: "Build JSON array", category: "json" },
    { name: "jsonb_build_array", signature: "jsonb_build_array(val1, ...)", description: "Build JSONB array", category: "json" },
    { name: "json_extract_path", signature: "json_extract_path(json, key1, ...)", description: "Extract JSON path", category: "json" },
    { name: "jsonb_extract_path", signature: "jsonb_extract_path(jsonb, key1, ...)", description: "Extract JSONB path", category: "json" },
    { name: "json_extract_path_text", signature: "json_extract_path_text(json, key1, ...)", description: "Extract JSON path as text", category: "json" },
    { name: "jsonb_extract_path_text", signature: "jsonb_extract_path_text(jsonb, key1, ...)", description: "Extract JSONB path as text", category: "json" },
    { name: "json_array_length", signature: "json_array_length(json)", description: "JSON array length", category: "json" },
    { name: "jsonb_array_length", signature: "jsonb_array_length(jsonb)", description: "JSONB array length", category: "json" },
    { name: "json_each", signature: "json_each(json)", description: "Expand JSON to key-value rows", category: "json" },
    { name: "jsonb_each", signature: "jsonb_each(jsonb)", description: "Expand JSONB to key-value rows", category: "json" },
    { name: "json_each_text", signature: "json_each_text(json)", description: "Expand JSON to text key-value rows", category: "json" },
    { name: "jsonb_each_text", signature: "jsonb_each_text(jsonb)", description: "Expand JSONB to text key-value rows", category: "json" },
    { name: "json_object_keys", signature: "json_object_keys(json)", description: "Get JSON object keys", category: "json" },
    { name: "jsonb_object_keys", signature: "jsonb_object_keys(jsonb)", description: "Get JSONB object keys", category: "json" },
    { name: "json_typeof", signature: "json_typeof(json)", description: "Type of JSON value", category: "json" },
    { name: "jsonb_typeof", signature: "jsonb_typeof(jsonb)", description: "Type of JSONB value", category: "json" },
    { name: "jsonb_set", signature: "jsonb_set(target, path, new_value)", description: "Set JSONB value at path", category: "json" },
    { name: "jsonb_insert", signature: "jsonb_insert(target, path, new_value)", description: "Insert JSONB value at path", category: "json" },
    { name: "jsonb_pretty", signature: "jsonb_pretty(jsonb)", description: "Pretty-print JSONB", category: "json" },
    { name: "jsonb_strip_nulls", signature: "jsonb_strip_nulls(jsonb)", description: "Remove null values from JSONB", category: "json" },
    { name: "to_json", signature: "to_json(value)", description: "Convert to JSON", category: "json" },
    { name: "to_jsonb", signature: "to_jsonb(value)", description: "Convert to JSONB", category: "json" },
    { name: "json_populate_record", signature: "json_populate_record(base, json)", description: "Expand JSON to record", category: "json" },
    { name: "jsonb_populate_record", signature: "jsonb_populate_record(base, jsonb)", description: "Expand JSONB to record", category: "json" },
    { name: "json_to_record", signature: "json_to_record(json)", description: "Convert JSON to record", category: "json" },
    { name: "jsonb_to_record", signature: "jsonb_to_record(jsonb)", description: "Convert JSONB to record", category: "json" },
    { name: "row_to_json", signature: "row_to_json(record)", description: "Convert record to JSON", category: "json" },

    // Array functions
    { name: "array_length", signature: "array_length(array, dimension)", description: "Array length", category: "array" },
    { name: "array_dims", signature: "array_dims(array)", description: "Array dimensions", category: "array" },
    { name: "array_lower", signature: "array_lower(array, dimension)", description: "Array lower bound", category: "array" },
    { name: "array_upper", signature: "array_upper(array, dimension)", description: "Array upper bound", category: "array" },
    { name: "array_append", signature: "array_append(array, element)", description: "Append to array", category: "array" },
    { name: "array_prepend", signature: "array_prepend(element, array)", description: "Prepend to array", category: "array" },
    { name: "array_cat", signature: "array_cat(array1, array2)", description: "Concatenate arrays", category: "array" },
    { name: "array_remove", signature: "array_remove(array, element)", description: "Remove element from array", category: "array" },
    { name: "array_replace", signature: "array_replace(array, from, to)", description: "Replace element in array", category: "array" },
    { name: "array_position", signature: "array_position(array, element)", description: "Position of element", category: "array" },
    { name: "array_positions", signature: "array_positions(array, element)", description: "All positions of element", category: "array" },
    { name: "array_to_string", signature: "array_to_string(array, delimiter)", description: "Join array to string", category: "array" },
    { name: "string_to_array", signature: "string_to_array(string, delimiter)", description: "Split string to array", category: "array" },
    { name: "unnest", signature: "unnest(array)", description: "Expand array to rows", category: "array" },
    { name: "cardinality", signature: "cardinality(array)", description: "Total number of elements", category: "array" },

    // Conditional / control
    { name: "coalesce", signature: "coalesce(val1, val2, ...)", description: "First non-null value", category: "conditional" },
    { name: "nullif", signature: "nullif(val1, val2)", description: "Null if equal", category: "conditional" },
    { name: "greatest", signature: "greatest(val1, val2, ...)", description: "Largest value", category: "conditional" },
    { name: "least", signature: "least(val1, val2, ...)", description: "Smallest value", category: "conditional" },

    // Type casting / info
    { name: "cast", signature: "cast(value AS type)", description: "Type cast", category: "type" },
    { name: "pg_typeof", signature: "pg_typeof(expression)", description: "Data type of expression", category: "type" },

    // System / info
    { name: "current_user", signature: "current_user", description: "Current user name", category: "system" },
    { name: "current_database", signature: "current_database()", description: "Current database name", category: "system" },
    { name: "current_schema", signature: "current_schema()", description: "Current schema name", category: "system" },
    { name: "current_setting", signature: "current_setting(name)", description: "Current config setting", category: "system" },
    { name: "pg_table_size", signature: "pg_table_size(regclass)", description: "Table disk size", category: "system" },
    { name: "pg_total_relation_size", signature: "pg_total_relation_size(regclass)", description: "Total relation size", category: "system" },
    { name: "pg_size_pretty", signature: "pg_size_pretty(bigint)", description: "Human-readable size", category: "system" },
    { name: "pg_column_size", signature: "pg_column_size(any)", description: "Bytes for stored value", category: "system" },
    { name: "pg_relation_size", signature: "pg_relation_size(regclass)", description: "Relation disk size", category: "system" },
    { name: "obj_description", signature: "obj_description(oid, catalog)", description: "Object comment", category: "system" },
    { name: "col_description", signature: "col_description(table_oid, column_number)", description: "Column comment", category: "system" },
    { name: "has_table_privilege", signature: "has_table_privilege(user, table, privilege)", description: "Check table privilege", category: "system" },
    { name: "has_schema_privilege", signature: "has_schema_privilege(user, schema, privilege)", description: "Check schema privilege", category: "system" },
    { name: "txid_current", signature: "txid_current()", description: "Current transaction ID", category: "system" },
    { name: "pg_backend_pid", signature: "pg_backend_pid()", description: "Backend process ID", category: "system" },
    { name: "pg_cancel_backend", signature: "pg_cancel_backend(pid)", description: "Cancel backend query", category: "system" },
    { name: "pg_terminate_backend", signature: "pg_terminate_backend(pid)", description: "Terminate backend", category: "system" },
    { name: "pg_stat_activity", signature: "pg_stat_activity", description: "Active sessions view", category: "system" },
    { name: "version", signature: "version()", description: "PostgreSQL version", category: "system" },

    // Sequence
    { name: "nextval", signature: "nextval(regclass)", description: "Next sequence value", category: "sequence" },
    { name: "currval", signature: "currval(regclass)", description: "Current sequence value", category: "sequence" },
    { name: "setval", signature: "setval(regclass, bigint)", description: "Set sequence value", category: "sequence" },
    { name: "lastval", signature: "lastval()", description: "Last sequence value", category: "sequence" },

    // UUID
    { name: "gen_random_uuid", signature: "gen_random_uuid()", description: "Generate random UUID", category: "uuid" },
    { name: "uuid_generate_v4", signature: "uuid_generate_v4()", description: "Generate v4 UUID (uuid-ossp)", category: "uuid" },
];
