const hslVar = (name: string) => `hsl(var(--${name}))`;

export const semanticColorTokens = {
  background: "background",
  foreground: "foreground",
  surface: "surface",
  surfaceRaised: "surface-raised",
  surfaceSubtle: "surface-subtle",
  textMuted: "text-muted",
  textSubtle: "text-subtle",
  card: "card",
  cardForeground: "card-foreground",
  popover: "popover",
  popoverForeground: "popover-foreground",
  primary: "primary",
  primaryForeground: "primary-foreground",
  secondary: "secondary",
  secondaryForeground: "secondary-foreground",
  muted: "muted",
  mutedForeground: "muted-foreground",
  accent: "accent",
  accentForeground: "accent-foreground",
  destructive: "destructive",
  destructiveForeground: "destructive-foreground",
  border: "border",
  borderSubtle: "border-subtle",
  borderStrong: "border-strong",
  input: "input",
  ring: "ring",
  focusRing: "focus-ring",
  success: "success",
  warning: "warning",
  info: "info",
} as const;

export const designTokenThemes = {
  light: {
    background: "0 0% 100%",
    foreground: "0 0% 6%",
    surface: "0 0% 100%",
    surfaceRaised: "0 0% 100%",
    surfaceSubtle: "0 0% 98%",
    textMuted: "0 0% 45%",
    textSubtle: "0 0% 64%",
    card: "0 0% 100%",
    cardForeground: "0 0% 6%",
    popover: "0 0% 100%",
    popoverForeground: "0 0% 6%",
    primary: "0 0% 9%",
    primaryForeground: "0 0% 98%",
    secondary: "0 0% 96%",
    secondaryForeground: "0 0% 9%",
    muted: "0 0% 96%",
    mutedForeground: "0 0% 45%",
    accent: "0 0% 96%",
    accentForeground: "0 0% 9%",
    destructive: "0 84% 60%",
    destructiveForeground: "0 0% 98%",
    border: "0 0% 90%",
    borderSubtle: "0 0% 90%",
    borderStrong: "0 0% 72%",
    input: "0 0% 90%",
    ring: "0 0% 9%",
    focusRing: "212 100% 48%",
    success: "142 72% 29%",
    warning: "38 92% 42%",
    info: "212 100% 48%",
  },
  dark: {
    background: "0 0% 4%",
    foreground: "0 0% 98%",
    surface: "0 0% 4%",
    surfaceRaised: "0 0% 7%",
    surfaceSubtle: "0 0% 10%",
    textMuted: "0 0% 64%",
    textSubtle: "0 0% 45%",
    card: "0 0% 4%",
    cardForeground: "0 0% 98%",
    popover: "0 0% 4%",
    popoverForeground: "0 0% 98%",
    primary: "0 0% 98%",
    primaryForeground: "0 0% 9%",
    secondary: "0 0% 15%",
    secondaryForeground: "0 0% 98%",
    muted: "0 0% 15%",
    mutedForeground: "0 0% 64%",
    accent: "0 0% 15%",
    accentForeground: "0 0% 98%",
    destructive: "0 62% 30%",
    destructiveForeground: "0 0% 98%",
    border: "0 0% 15%",
    borderSubtle: "0 0% 15%",
    borderStrong: "0 0% 28%",
    input: "0 0% 15%",
    ring: "0 0% 84%",
    focusRing: "212 100% 58%",
    success: "142 70% 45%",
    warning: "38 92% 56%",
    info: "212 100% 58%",
  },
} as const;

export const componentTokens = {
  controlHeight: {
    xs: "1.5rem",
    sm: "1.75rem",
    md: "2rem",
  },
  toolbarHeight: "2rem",
  iconSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
  },
  panel: {
    radius: "0.375rem",
    border: hslVar(semanticColorTokens.borderSubtle),
    surface: hslVar(semanticColorTokens.surface),
    raisedSurface: hslVar(semanticColorTokens.surfaceRaised),
  },
  code: {
    background: hslVar(semanticColorTokens.surfaceSubtle),
    foreground: hslVar(semanticColorTokens.foreground),
  },
} as const;

export const designTokens = {
  color: {
    primitive: {
      neutral0: "#ffffff",
      neutral50: "#fafafa",
      neutral100: "#f4f4f5",
      neutral200: "#e4e4e7",
      neutral300: "#d4d4d8",
      neutral500: "#71717a",
      neutral700: "#3f3f46",
      neutral900: "#18181b",
      neutral950: "#09090b",
    },
    semantic: {
      background: hslVar(semanticColorTokens.background),
      foreground: hslVar(semanticColorTokens.foreground),
      surface: hslVar(semanticColorTokens.surface),
      surfaceRaised: hslVar(semanticColorTokens.surfaceRaised),
      surfaceSubtle: hslVar(semanticColorTokens.surfaceSubtle),
      textMuted: hslVar(semanticColorTokens.textMuted),
      textSubtle: hslVar(semanticColorTokens.textSubtle),
      borderSubtle: hslVar(semanticColorTokens.borderSubtle),
      borderStrong: hslVar(semanticColorTokens.borderStrong),
      focusRing: hslVar(semanticColorTokens.focusRing),
    },
  },
  space: {
    0: "0",
    0.5: "0.125rem",
    1: "0.25rem",
    1.5: "0.375rem",
    2: "0.5rem",
    2.5: "0.625rem",
    3: "0.75rem",
    4: "1rem",
    6: "1.5rem",
    8: "2rem",
  },
  radius: {
    none: "0",
    xs: "0.125rem",
    sm: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    full: "9999px",
  },
  size: {
    controlXs: componentTokens.controlHeight.xs,
    controlSm: componentTokens.controlHeight.sm,
    controlMd: componentTokens.controlHeight.md,
    toolbar: componentTokens.toolbarHeight,
    iconXs: componentTokens.iconSize.xs,
    iconSm: componentTokens.iconSize.sm,
    iconMd: componentTokens.iconSize.md,
  },
  shadow: {
    ring: "0 0 0 1px hsl(var(--border-subtle))",
    raised: "0 0 0 1px hsl(var(--border-subtle)), 0 2px 8px hsl(var(--foreground) / 0.08)",
    overlay: "0 0 0 1px hsl(var(--border-subtle)), 0 12px 32px hsl(var(--foreground) / 0.16)",
  },
  typography: {
    label: {
      fontSize: "0.75rem",
      lineHeight: "1rem",
      fontWeight: "500",
    },
    body: {
      fontSize: "0.875rem",
      lineHeight: "1.25rem",
      fontWeight: "400",
    },
    mono: {
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      fontSize: "0.75rem",
      lineHeight: "1rem",
      fontWeight: "500",
    },
  },
  motion: {
    durationFast: "120ms",
    durationDefault: "180ms",
    easingDefault: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
} as const;

export type DesignTokens = typeof designTokens;
export type SemanticColorToken = keyof typeof semanticColorTokens;

export const tailwindThemeTokens = {
  colors: {
    border: hslVar(semanticColorTokens.border),
    input: hslVar(semanticColorTokens.input),
    ring: hslVar(semanticColorTokens.ring),
    focus: hslVar(semanticColorTokens.focusRing),
    background: hslVar(semanticColorTokens.background),
    foreground: hslVar(semanticColorTokens.foreground),
    surface: {
      DEFAULT: hslVar(semanticColorTokens.surface),
      raised: hslVar(semanticColorTokens.surfaceRaised),
      subtle: hslVar(semanticColorTokens.surfaceSubtle),
    },
    text: {
      muted: hslVar(semanticColorTokens.textMuted),
      subtle: hslVar(semanticColorTokens.textSubtle),
    },
    success: hslVar(semanticColorTokens.success),
    warning: hslVar(semanticColorTokens.warning),
    info: hslVar(semanticColorTokens.info),
    primary: {
      DEFAULT: hslVar(semanticColorTokens.primary),
      foreground: hslVar(semanticColorTokens.primaryForeground),
    },
    secondary: {
      DEFAULT: hslVar(semanticColorTokens.secondary),
      foreground: hslVar(semanticColorTokens.secondaryForeground),
    },
    destructive: {
      DEFAULT: hslVar(semanticColorTokens.destructive),
      foreground: hslVar(semanticColorTokens.destructiveForeground),
    },
    muted: {
      DEFAULT: hslVar(semanticColorTokens.muted),
      foreground: hslVar(semanticColorTokens.mutedForeground),
    },
    accent: {
      DEFAULT: hslVar(semanticColorTokens.accent),
      foreground: hslVar(semanticColorTokens.accentForeground),
    },
    popover: {
      DEFAULT: hslVar(semanticColorTokens.popover),
      foreground: hslVar(semanticColorTokens.popoverForeground),
    },
    card: {
      DEFAULT: hslVar(semanticColorTokens.card),
      foreground: hslVar(semanticColorTokens.cardForeground),
    },
  },
  borderRadius: {
    lg: "var(--radius)",
    md: "calc(var(--radius) - 2px)",
    sm: "calc(var(--radius) - 4px)",
  },
  spacing: {
    toolbar: componentTokens.toolbarHeight,
    "control-xs": componentTokens.controlHeight.xs,
    "control-sm": componentTokens.controlHeight.sm,
    "control-md": componentTokens.controlHeight.md,
  },
  boxShadow: {
    ring: designTokens.shadow.ring,
    raised: designTokens.shadow.raised,
    overlay: designTokens.shadow.overlay,
  },
} as const;
