"""Database migration commands."""

from __future__ import annotations

import typer

from cli.process import run_alembic

app = typer.Typer(help="Database migration commands.", no_args_is_help=False)


@app.callback(invoke_without_command=True)
def migrate_callback(ctx: typer.Context) -> None:
    """Run pending migrations, or use a migration subcommand."""
    if ctx.invoked_subcommand is None:
        run_alembic("upgrade", "head")


@app.command("new")
def new(name: str = typer.Argument(..., help="Migration message")) -> None:
    """Create a new autogenerated migration."""
    run_alembic("revision", "--autogenerate", "-m", name)


@app.command("up")
def up(revision: str = typer.Argument("head", help="Revision to upgrade to")) -> None:
    """Upgrade to a revision."""
    run_alembic("upgrade", revision)


@app.command("down")
def down(revision: str = typer.Argument("-1", help="Revision to downgrade to")) -> None:
    """Downgrade to a revision."""
    run_alembic("downgrade", revision)


@app.command("history")
def history() -> None:
    """Show migration history."""
    run_alembic("history", "--verbose")


@app.command("current")
def current() -> None:
    """Show the current migration revision."""
    run_alembic("current")


@app.command("stamp")
def stamp(revision: str = typer.Argument(..., help="Revision to stamp")) -> None:
    """Stamp the database without running migrations."""
    run_alembic("stamp", revision)
