"""add_app_settings_table

Revision ID: 93f16d53a438
Revises: aeb0e5aad206
Create Date: 2026-04-16 18:33:50.418570
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93f16d53a438'
down_revision: Union[str, None] = 'aeb0e5aad206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
