"""expand api key prefix length

Revision ID: bf8ef446249a
Revises: e1a2b3c4d5f6
Create Date: 2026-05-04 23:55:26.118857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf8ef446249a'
down_revision: Union[str, None] = 'e1a2b3c4d5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_queries', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_queries', 'api_key_prefix',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
