"""add_secret_key_to_users

Revision ID: ce50418e4dc1
Revises: 93f16d53a438
Create Date: 2026-04-16 19:31:07.147011
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce50418e4dc1'
down_revision: Union[str, None] = '93f16d53a438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('secret_key', sa.String(length=64), nullable=True))
    # Backfill existing users with auto-generated secret keys
    import secrets
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id FROM users WHERE secret_key IS NULL")).fetchall()
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789"
    for (user_id,) in users:
        key = "".join(secrets.choice(alphabet) for _ in range(12))
        conn.execute(sa.text("UPDATE users SET secret_key = :key WHERE id = :id"), {"key": key, "id": user_id})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_key')
    # ### end Alembic commands ###
